services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: sentia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

  sentia:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    
    environment:
      # Fuso horário para o container
      TZ: America/Sao_Paulo

      # Variáveis para conexão com o banco de dados
      DB_HOST: postgres
      DB_NAME: sentia
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432

    networks:
      - app-network
    depends_on:
      - postgres
      - ollama

networks:
  app-network:
    name: sentia-network

volumes:
  postgres_data:
  ollama_data: