# Generated by Django 5.2.6 on 2025-09-18 21:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Análise')),
                ('csv_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Arquivo CSV')),
            ],
            options={
                'verbose_name': 'Sessão de Análise',
                'verbose_name_plural': 'Sessões de Análise',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto do Feedback')),
                ('sentiment', models.CharField(choices=[('POS', 'Positivo'), ('NEG', 'Negativo'), ('NEU', 'Neutro'), ('UNKN', 'Desconhecido')], default='UNKN', max_length=4, verbose_name='Sentimento')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Cliente')),
                ('feedback_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Feedback')),
                ('product_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área do Produto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='sentia.analysissession', verbose_name='Sessão de Análise')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
