# Generated by Django 5.2.6 on 2025-09-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='session_number',
            field=models.IntegerField(null=True, unique=True, verbose_name='Número da Sessão'),
        ),
    ]
