# Generated by Django 5.2.6 on 2025-09-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentia', '0002_analysissession_session_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysissession',
            name='session_number',
            field=models.IntegerField(unique=True, verbose_name='Número da Sessão'),
        ),
    ]
