# Generated by Django 5.2.6 on 2025-09-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentia', '0003_alter_analysissession_session_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Feedback'),
        ),
    ]
